name: Test

on:
  push:
  pull_request:

jobs:
  verilog:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y iverilog expect

      - name: Run tests
        run: make test
